#!/usr/bin/env bash
# Local-network HTTPS for real-device testing (camera APIs require HTTPS; phones cannot reach localhost).
# Creates a development certificate for localhost + this Mac's LAN IP, used by the web app and MinIO.
# Demo data only. Nothing is exposed to the internet.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CERTS="$ROOT/ops/dev-https/certs"

if ! command -v mkcert >/dev/null; then
  echo "mkcert is not installed. Run:  brew install mkcert nss" >&2
  exit 1
fi

IP="${1:-$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)}"
if [[ -z "$IP" ]]; then
  echo "Could not find this Mac's Wi-Fi IP. Pass it explicitly:  pnpm https:setup 192.168.1.20" >&2
  exit 1
fi

echo "→ Installing the development certificate authority on this Mac (asks for your password)"
mkcert -install

echo "→ Creating a certificate for localhost and $IP"
mkdir -p "$CERTS/minio"
mkcert -cert-file "$CERTS/lan.pem" -key-file "$CERTS/lan-key.pem" localhost 127.0.0.1 ::1 "$IP"
cp "$CERTS/lan.pem" "$CERTS/minio/public.crt"
cp "$CERTS/lan-key.pem" "$CERTS/minio/private.key"

CAROOT="$(mkcert -CAROOT)"
# Copies to install on the phones (iPhone accepts .pem, Android needs .crt).
cp "$CAROOT/rootCA.pem" "$CERTS/ResortOS-dev-CA.pem"
cp "$CAROOT/rootCA.pem" "$CERTS/ResortOS-dev-CA.crt"

cat > "$ROOT/.env.lan" <<ENV
# Generated by ops/dev-https/setup-lan.sh — overrides .env for phone testing on the local network.
LAN_IP=$IP
WEB_ORIGIN=https://$IP:3000
PUBLIC_WEB_URL=https://$IP:3000
S3_ENDPOINT=https://localhost:9000
S3_PUBLIC_ENDPOINT=https://$IP:9000
DEV_ALLOWED_ORIGINS=$IP
MKCERT_CA=$CAROOT/rootCA.pem
ENV

echo "→ Restarting MinIO with HTTPS"
(cd "$ROOT" && docker compose up -d --force-recreate --wait minio >/dev/null && docker compose run --rm minio-init >/dev/null)

cat <<DONE

✓ HTTPS ready for $IP

Start the apps in two terminals:
    pnpm dev:api:lan
    pnpm dev:web:lan

Desk:   https://$IP:3000   (or https://localhost:3000)
Phone certificate files:
    $CERTS/ResortOS-dev-CA.pem   (iPhone)
    $CERTS/ResortOS-dev-CA.crt   (Android)
See docs/phone-testing.md for installing them.
DONE
